name = "croche-backend"
main = "worker.ts"
compatibility_date = "2023-10-30"
node_compat = true

[build]
command = "pnpm build"

[build.upload]
format = "service-worker"

# Your environment variables
[vars]
DATABASE_URL="mongodb+srv://manavadwani86:2Sri82z1RuQogjOo@croche.sf0dl.mongodb.net/croche?retryWrites=true&w=majority&appName=Croche"
CLOUDINARY_CLOUD_NAME="drqmbolxi"
CLOUDINARY_API_KEY="813534687278347"
CLOUDINARY_API_SECRET="eSZicaSIN0z7KIe_Hr4N-q5TVjw"
JWT_SECRET="4w6E&9f0Vx8!bZr1yT2@k8LmT@u3dX9eYqz6kF3iDWs0U4oZzA!pC8d"
RESEND_API_KEY="re_V64iHPBk_5umpDbZjQ8E31SjNr4i1XwMQ "
ADMIN_EMAIL="manavadwani5@gmail.com"
RESEND_FROM_EMAIL="Croche <order@croche.parthsinha.com>"
NODE_ENV="development"
ALLOWED_ORIGINS="http://localhost:3000,http://localhost:4000,http://localhost:4321"
PORT="3000"
RATE_LIMIT_TTL="60"
RATE_LIMIT_MAX="10"